require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/purchase_categories', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # PurchaseCategory. As you add validations to PurchaseCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PurchaseCategory.create! valid_attributes
      get purchase_categories_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      purchase_category = PurchaseCategory.create! valid_attributes
      get purchase_category_url(purchase_category)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_purchase_category_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      purchase_category = PurchaseCategory.create! valid_attributes
      get edit_purchase_category_url(purchase_category)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PurchaseCategory' do
        expect do
          post purchase_categories_url, params: { purchase_category: valid_attributes }
        end.to change(PurchaseCategory, :count).by(1)
      end

      it 'redirects to the created purchase_category' do
        post purchase_categories_url, params: { purchase_category: valid_attributes }
        expect(response).to redirect_to(purchase_category_url(PurchaseCategory.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PurchaseCategory' do
        expect do
          post purchase_categories_url, params: { purchase_category: invalid_attributes }
        end.to change(PurchaseCategory, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post purchase_categories_url, params: { purchase_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested purchase_category' do
        purchase_category = PurchaseCategory.create! valid_attributes
        patch purchase_category_url(purchase_category), params: { purchase_category: new_attributes }
        purchase_category.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the purchase_category' do
        purchase_category = PurchaseCategory.create! valid_attributes
        patch purchase_category_url(purchase_category), params: { purchase_category: new_attributes }
        purchase_category.reload
        expect(response).to redirect_to(purchase_category_url(purchase_category))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        purchase_category = PurchaseCategory.create! valid_attributes
        patch purchase_category_url(purchase_category), params: { purchase_category: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested purchase_category' do
      purchase_category = PurchaseCategory.create! valid_attributes
      expect do
        delete purchase_category_url(purchase_category)
      end.to change(PurchaseCategory, :count).by(-1)
    end

    it 'redirects to the purchase_categories list' do
      purchase_category = PurchaseCategory.create! valid_attributes
      delete purchase_category_url(purchase_category)
      expect(response).to redirect_to(purchase_categories_url)
    end
  end
end
